### ISSUE TITLE
32 things to look at - for beta.shopping.io desktop and mobile version. + gspi.finance

### ISSUE THREAD

**Issue by RolfS02** [shoppingio/community-feedback#12]
Things to be fixed.

1. Order summery on frontpage is showing accumulated price and a picture of one of your orders. Looks like the price shown is the price for the product shown. 
2. Language settings should be added. Big one - I know. 
3. When you edit your address and type in your info and wants to save - The button should say “Save”. 
4. It’s not possible to subscribe to the newsletter in the footer. 
5. If you click on “explore” the SPI and GSPI token, you are taken to your “our packages”-section. Ok. Fine. But if you click “sign up” even though you already are signed up - you are left with absolutely no information about SPI or GSPI. 
6. Either FR, ES, IT not yet visible on the website even though it has been marketed.
7. SPIO not loading for certain wallets - showing wrong plans and wrong discounts
8. Extremely slow loading speed for product photos. Slow API.
9. Missing option for choosing categories. “Categories” are only showed in the featured items list on the frontpage.
10. After you’ve signed up all the “signup” buttons are still there all over the site. They should not be if you are logged in.
11. No Transak-integration visible on website. Impossible to find any links.
12. Missing dedicated “How to buy SPI and GSPI” menu item/section. Link to exchanges etc. Nothing there.
13. Missing videos and how to’s for staking. 
14. “VIP airdrop tiers for staking larger amounts of $GSPI”-mentioned but not specified anywhere.
15. The Altcoin daily video should be removed. It is shown here: https://beta.shopping.io/newsroom
16. The “Celebrity Endorsements” is the same page as “Youtube”. Seems odd.
17. Missing links to recents AMA’s here: https://beta.shopping.io/newsroom

  **For gspi.finance** 

18. It’s not even possible to create proposals on gspi.finance - even after the marketed incentives. Therefore absolutely no proposals.   

**Frontend issues/bugs from mobile experience - iPhone Xs**  

19. If I add something to my cart and clicks on the homepage, there’s no link to the cart anywhere. Only earlier orders showing on the frontpage. That is vital. 
20. If you add an order and cancels the order in Utrust, you’ll see order every time you login on the homepage. Needs to be cancelled if that is the case. 
21. No animations or visual appealing effects when loading the frontpage. Could be nice with just a little bit. 
22. Way too large line hight on the description - “the bridge behind crypto…..” Should be the same as in the info boxes “Save money” and “Shop with crypto”.
23. The link in the “Shop with crypto”-box goes to a search field and puts in “apple”. It should at least put in “Apple Watch” so it’s consistent with the picture shown on the frontpage. 
24. Search bar is kissing the edges. Looks quite bad. It needs at least 10px to each site. At minimum.
25. Search bar text cut in half. Should be adjusted.
26. “How it works”-section is way too airy. Space between the bullets are way too big and  the stacked icons do not work well with mobile. You need to scroll too much. Compare to e.g safemoon.net to look at space between the text-sections. (I don’t own any safemoon, but they have a nice website)
27. The “How it works”-section's last bullet “Check out” should be “Checkout” and the “start” button below is sliced 1/3. 
28. The foundation page has the big Iphone with a play icon containing the animation. Should be removed. Makes no sense and confuses people.
29. The buttons on foundation page are completely different than the ones on the frontpage. Different hight and border radius.
30. The “search” button on the foundational page is also different in design than the one on the frontpage
31. “Benefits”-section has a clickable animation as well. That should be removed. 
32. The “My account” menu shows a “night mode” option. Does not work. Very cool idea.
33. Overall there's a lot frontend to be fixed on the mobile version. But the pagespeed is vital. Critical with the API speed.

**Comment by cioshopping** [comment]
@RolfS02 I am closing this thread and extracting issues that have not been resolved.
