### ISSUE TITLE
Token validation issue, can't verify email address and no option to re-send verification

### ISSUE THREAD

**Issue by abatardi** [shoppingio/community-feedback#15]
### PAGE URL:  
Account registration / https://back.shopping.io/auth/email-confirmation?confirmation=<token>

### STEPS TO REPEAT (1,2,3,etc):  
1. Register for new account
2. Wait a few minutes for email
3. Click "Confirm Email" button

### SHORT DESCRIPTION: 
Account email verification fails with Bad Request (400) token.invalid error.  

### ISSUE:
JSON object returned:
{"statusCode":400, "error":"Bad Request", "message": "token.invalid"}

A couple more issues with this:
1) No friendly error message displayed to end user, instead raw JSON response is returned.
2) Apparently no method to retry the email confirmation flow.  Now user is "stuck" with invalid account, and can't add items to shopping cart or checkout.

**Comment by abatardi** [comment]
Also, once this happens, user is left in a completely "stuck" state where cart doesn't seem to clear, yet going to cart shows it is empty (API response shows all items in the cart, they just aren't being displayed on the page).

**Comment by softstack** [comment]
Hey @abatardi did you clicked twice on the button ?

**Comment by abatardi** [comment]
No idea. I guess if I had that would be another bug. Oh wait -- https://github.com/shoppingio/community-feedback/issues/18

**Comment by abatardi** [comment]
And even if I had doubled clicked and the front end had allowed that, there should be server side validation to prevent duplicate registration.

**Comment by abatardi** [comment]
> Hey @abatardi did you clicked twice on the button ?

Watch your language please.

**Comment by softstack** [comment]
Thanks for your helpful feedback, we are investigating into your problem. Unfortunately that problem is based on strapi (The CMS that is used by beta.shopping.io) https://forum.strapi.io/t/got-status-code-400-bad-request-from-auth-email-confirmation/1460/27 working on it.
