### ISSUE TITLE
Improvement: Display error/status toast message in upper right instead of bottom left

### ISSUE THREAD

**Issue by abatardi** [shoppingio/community-feedback#16]
### PAGE URL:  
Add to cart, etc.

### STEPS TO REPEAT (1,2,3,etc):  
1. Add item to cart
2. Toast message is displayed in bottom left corner. On a widescreen/ultra widescreen monitor this is effectively "hidden" from the user as it displays in the footer of the page where attention is not drawn.  

### SHORT DESCRIPTION: 
Toast messages are displayed in a bad location (footer), resulting in poor UX.  User is left feeling like nothing happened and the action failed. 

### ISSUE:
Poor UI/UX

**Comment by cioshopping** [comment]
Closing. Issue is on the old platform.
