### ISSUE TITLE
Improvement: Add Quantity input box on product page

### ISSUE THREAD

**Issue by abatardi** [shoppingio/community-feedback#17]
### PAGE URL:  
Product page

### STEPS TO REPEAT (1,2,3,etc):  
1. Go to product page
2. No "quantity" field available to user

### SHORT DESCRIPTION: 
No quantity available, user has to update quantities through cart page

### ISSUE:
Poor UI/UX

**Comment by softstack** [comment]
Fixed

**Comment by abatardi** [comment]
Are you kidding? You didn’t even add an input field label

**Comment by softstack** [comment]
Please watch your language. Check the product pages https://beta.shopping.io/product/ebay/v1%7C154260684946%7C454357698986
There is a quantity counter added
