### ISSUE TITLE
Add to Cart button does not disable after initial click

### ISSUE THREAD

**Issue by abatardi** [shoppingio/community-feedback#18]
### PAGE URL:  
Product info page

### STEPS TO REPEAT (1,2,3,etc):  
1. Double click "add to cart"
2. Two form posts are submitted, duplicate product is added

### SHORT DESCRIPTION: 
Add to cart button disable

### ISSUE:
It is standard practice to disable form action buttons immediately after click to prevent duplicate form submission which may result in unintended actions, problems, etc. Add to cart button (and any other relevant form submit actions) should be immediately disabled in js prior to processing the request, then re-enabled after some condition if needed (on ajax success/error response, after a certain amount of time like a couple seconds, etc.). 

Most UI libraries/reactive frameworks even have helper functions built in to do exactly this (stop event propogation, event.preventDefault();) such as Vue's "@click.stop" modifier.

**Comment by softstack** [comment]
Fixed
