### ISSUE TITLE
Cart: No product information available

### ISSUE THREAD

**Issue by HemAsthana** [shoppingio/community-feedback#2]
When you add a product to cart, there is no product information available.

User need to re-search the product to get information.![image](https://user-images.githubusercontent.com/41382540/118430126-a35bf700-b6d3-11eb-89d3-29e4b95d487f.png)![image](https://user-images.githubusercontent.com/41382540/118430136-a8b94180-b6d3-11eb-81a2-6039fb9ffde1.png)![image](https://user-images.githubusercontent.com/41382540/118430140-abb43200-b6d3-11eb-95c3-ffc8170953a6.png)![image](https://user-images.githubusercontent.com/41382540/118430144-aeaf2280-b6d3-11eb-8cbd-0ab240196172.png)

**Comment by Slazenby** [comment]
You are still using the old site. Try Beta.shopping.io

**Comment by softstack** [comment]
Issue is referring to the old website. But the new API seems to give us also no information 
https://beta.shopping.io/product/B086226DDB 

But we getting full information about variation
