### ISSUE TITLE
Add input field label for quantity box on product page

### ISSUE THREAD

**Issue by abatardi** [shoppingio/community-feedback#23]
It’s embarrassing that I even need to file this but you need to ALSO add some type of field label on the new quantity input box on the product page. 

https://github.com/shoppingio/community-feedback/issues/17

![36C92F5E-0791-4C71-BE8D-F807DABC275B](https://user-images.githubusercontent.com/450006/123095512-26235080-d3fc-11eb-8e2b-592057e7a331.jpeg)

**Comment by softstack** [comment]
Thanks for your feedback, we will add that label

**Comment by softstack** [comment]
Quantity label got added https://beta.shopping.io/product/ebay/v1%7C274505797468%7C574685374493
