### ISSUE TITLE
No clarity on total product worth

### ISSUE THREAD

**Issue by HemAsthana** [shoppingio/community-feedback#3]
When you search for a product, which has international shipping. Reference: Order #29088

You have following cost.

1. Actual product cost (e.g., Amazon)
2. Shipping cost
3. Import cost

Actual product cost is well implemented and user journey is seamless.

However for shipping cost. I have few feedback / issue.

A. What I understand, shipping cost is based on weight and destination of the package. As you would know at time of placing the order the address, it would be nice if the user get to know. What they are paying and doesn't wait to have a chat with an agent to fulfil the order.

B. Email is sent stating "A note has been added to your order". When I search for the order on shopping.io >> orders. I do not see any note.

C. In e-mail it also states "Kindly send payment via Crypto if you wish to continue". However there is no payment link.

D. There are few payment method for shipping cost (Eth or SPI).

For B / C / D. I placed order via Crypto.com CRO coins. I was expecting I could pay with it and arranged it accordingly.

However when I had a chat, then I came to know, only Eth or SPI is acceptable, 

Either inform user upfront, to save their transactions cost (buying CRO then converting to Eth) or make it visible that shipping cost payment via SPI or Eth.

Preference: Once SPI is rolled out to major exchanges, then only keep SPI as shipping fees. This would create demand for token.

Also expecting automated process for shipping related activities.

E. I might be asking too much on this. If possible and available and you can place a link for import tax that user might be getting into for importing goods which are internationally shipped.

**Comment by cioshopping** [comment]
Closing. Issue is on the old platform.
