### ISSUE TITLE
product search 

### ISSUE THREAD

**Issue by Immediateclub** [shoppingio/community-feedback#30]
Your search did not match any products   
the search engine sometimes fails to find ASIN

**Comment by cioshopping** [comment]
Is this on Version 1 or Version 2 Beta?
Can you post the ASIN that didn't work?

**Comment by Immediateclub** [comment]
Actually both   
i bought this a while ago   now its not working

ASIN(B08NQ17JYJ)
https://www.amazon.com/gp/product/B08NQ17JYJ?pf_rd_r=KNFXFNVB7EDRVYJR419E&pf_rd_p=6fc81c8c-2a38-41c6-a68a-f78c79e7253f&pd_rd_r=9a1159dd-02c8-4cdf-828f-cf0b2619b827&pd_rd_w=aJhuD&pd_rd_wg=S6OFY&ref_=pd_gw_unk

**Comment by cioshopping** [comment]
It looks like this product is unavailable on Amazon. 

Do you have an example of an ASIN where the product is available on Amazon but not showing on our site? Let me know if you come across one.

**Comment by Immediateclub** [comment]
products over 1k is not supported at the moment
