### ISSUE TITLE
Featured and new items list can be misleading for new visitors on how many products are available through shopping.io

### ISSUE THREAD

**Issue by LaszloOveges** [shoppingio/community-feedback#35]
### PAGE URL:  
https://us.shopping.io/search?category=featured

### STEPS TO REPEAT:  
1. open the new version of the website at https://us.shopping.io/
2. scroll down on the main page looking for products or simply click on the Explore button, then choose Featured items or New listing or a single category
3. On the next page it is not clear for the users (other than the url has a ?category=featured query in it) that the list only shows a selected group of products, and the user cannot step back from it to search in a greater scope.

### SHORT DESCRIPTION: 
The problem is that on the result page, there is no sign of what category, filter or keyword has been used to filter the results and there is no option to change that or step back from it to see a greater scope. Only option is to start a new search.

### ISSUE:
A new visitors first experience with the low number of available products can be disappointing.

**Comment by cioshopping** [comment]
Closing. Issue is not on the new platform.
