### ISSUE TITLE
link leading to http://127.0.0.1/Shopping.io-V2-to-V1

### ISSUE THREAD

**Issue by Shvekey** [shoppingio/community-feedback#41]
### PAGE URL:  
https://shopping.io/#howitworks

### STEPS TO REPEAT (1,2,3,etc):  
1. go to "how it works" section of the website
2. click on the word "Explore"
3. get to http://127.0.0.1/Shopping.io-V2-to-V1

### SHORT DESCRIPTION: 
you have some left overs from dev team... the link behind the word "explore" leads to local machine (as described above)

### ISSUE:
Same as title and description. you will figure it out ;)

**Comment by cioshopping** [comment]
Resolved. Thank you for reporting this. :)
