### ISSUE TITLE
Missing hyperlink 

### ISSUE THREAD

**Issue by Slazenby** [shoppingio/community-feedback#7]
PAGE URL:  https://beta.shopping.io/ecosystem

STEPS TO REPEAT (1,2,3,etc): Scroll to bottom of page, read

SHORT DESCRIPTION: Hyperlink appears to be missing - 

"For a deeper look into the ( SPI / GSPI ) tokens on the Shopping.io platform please view our Tokenomics Page here. ( ← Hyperlink to [ TOKENOMICS ] page / @ home footer."

ISSUE: Hyperlink missing

**Comment by softstack** [comment]
Fixed https://beta.shopping.io/ecosystem
