### ISSUE TITLE
Missing Trustpilot hyperlink in the footer

### ISSUE THREAD

**Issue by pkusmirowski** [shoppingio/community-feedback#8]
PAGE URL:  
https://beta.shopping.io/

STEPS TO REPEAT:  
1. Footer at the bottom of the page

SHORT DESCRIPTION: 
The Trustpilot hyperlink refreshes the current page. Should open Trustpilot website.

ISSUE:
No hyperlink to Trustpilot in the footer

Additionally:
Also there are no hyperlinks to social media under Stay in the Loop on this site https://beta.shopping.io/newsroom

**Comment by softstack** [comment]
Fixed 
https://beta.shopping.io/
https://beta.shopping.io/foundation
